# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ring-event-collector # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python2.7
  timeout: 300
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: "*"

functions:
  collect:
    handler: handler.collect
    events:
      - schedule: rate(5 minutes)
    environment:
      USER: ${file(secrets.yml):USER}
      PASS: ${file(secrets.yml):PASS}

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ring-device-events
        AttributeDefinitions:
          - AttributeName: device
            AttributeType: S
          - AttributeName: event_timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: device
            KeyType: HASH
          - AttributeName: event_timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
